# Generated by Django 6.0.4 on 2026-04-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='terefaModel',
            new_name='tarefaModel',
        ),
    ]
